version: '3'

volumes:
  mongo_db: {}
  mongo_configdb: {}
  psql_data: {}
  ts_data: {}
  pipeline_data: {}
  mysql_data: {}
  rabbit_data: {}
  redis_data: {}
  influx_data: {}
  nsqd_data: {}
  tarantool_data: {}

services:

  tarantool:
    image: tarantool/tarantool:2
    container_name: tarantool
    restart: always
    expose:
      - 3301
    network_mode: "host"
    volumes:
      - "tarantool_data:/var/lib/tarantool"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    network_mode: "host"
    volumes:
      - "mongo_db:/data/db"
      - "mongo_configdb:/data/configdb"

  psql:
    image: postgres:alpine
    container_name: psql
    restart: always
    expose:
      - 5432
    network_mode: "host"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - "psql_data:/var/lib/postgresql/data"

  ts:
    image: timescale/timescaledb:latest-pg11
    container_name: ts
    restart: always
    expose:
      - 5432
    network_mode: "host"
    environment:
      POSTGRES_USER: ${TS_USER}
      POSTGRES_PASSWORD: ${TS_PASS}
      POSTGRES_DB: ${TS_DB}
    volumes:
      - "ts_data:/var/lib/postgresql/data"

  pipeline:
    image: pipelinedb/pipelinedb-postgresql-11
    container_name: pipeline
    restart: always
    expose:
      - 5433
    network_mode: "host"
    environment:
      POSTGRES_USER: ${PIPELINE_USER}
      POSTGRES_PASSWORD: ${PIPELINE_PASS}
      POSTGRES_DB: ${PIPELINE_DB}
    volumes:
      - "pipeline_data:/var/lib/postgresql/data"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    expose:
      - 3306
    network_mode: "host"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    restart: always
    expose:
      - 5672
      - 15672
    network_mode: "host"
    volumes:
      - "rabbit_data:/var/lib/rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VHOST}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    network_mode: "host"
    volumes:
      - "redis_data:/data"

  influx:
    image: influxdb
    container_name: influx
    restart: always
    expose:
      - 8086
      - 8083
    network_mode: "host"
    volumes:
      - "influx_data:/var/lib/influxdb"
    environment:
      INFLUXDB_ADMIN_ENABLED: ${INFLUX_ADMIN}
      INFLUXDB_ADMIN_USER: ${INFLUX_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUX_ADMIN_PASS}

  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    container_name: nsqlookupd
    command: /nsqlookupd
    network_mode: "host"
    expose:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq:v1.2.0
    container_name: nsqd
    command: /nsqd --lookupd-tcp-address=127.0.0.1:4160 --data-path=/data
    network_mode: "host"
    depends_on:
      - nsqlookupd
    expose:
      - "4150"
      - "4151"
    volumes:
      - "nsqd_data:/data"

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
    network_mode: "host"
    depends_on:
      - nsqlookupd  
    expose:
      - "4171"
