version: '3'
services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    network_mode: "host"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    network_mode: "host"
    volumes:
      - "mongo:/data/db"

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    restart: always
    expose:
      - 5672
      - 15672
    network_mode: "host"
    volumes:
      - "rabbit:/var/lib/rabbit"

volumes:
  postgres: {}
  mongo: {}
  rabbit: {}
