version: '3'

volumes:
  mongo_db: {}
  mongo_configdb: {}
  psql_data: {}
  mysql_data: {}
  rabbit_data: {}
  redis_data: {}
  influx_data: {}
  nsq_data: {}

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    network_mode: "host"
    volumes:
      - "mongo_db:/data/db"
      - "mongo_configdb:/data/configdb"

  psql:
    image: postgres:alpine
    container_name: psql
    restart: always
    expose:
      - 5432
    network_mode: "host"
    volumes:
      - "psql_data:/var/lib/postgresql/data"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    expose:
      - 3306
    network_mode: "host"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    restart: always
    expose:
      - 5672
      - 15672
    network_mode: "host"
    volumes:
      - "rabbit_data:/var/lib/rabbit"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    network_mode: "host"
    volumes:
      - "redis_data:/data"

  influx:
    image: influxdb
    container_name: influx
    restart: always
    expose:
      - 8086
      - 8083
    network_mode: "host"
    volumes:
      - "influx_data:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=influxdb"
      - "INFLUXDB_ADMIN_PASSWORD=influxdb"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    network_mode: "host"
    expose:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=127.0.0.1:4160 --data-path=/data
    network_mode: "host"
    depends_on:
      - nsqlookupd
    expose:
      - "4150"
      - "4151"
    volumes:
      - "nsqd_data:/data"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
    network_mode: "host"
    depends_on:
      - nsqlookupd  
    expose:
      - "4171"
