version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    network_mode: "host"
    volumes:
      - "mongo:/data/db"

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    network_mode: "host"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    expose:
      - 3306
    network_mode: "host"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    restart: always
    expose:
      - 5672
      - 15672
    network_mode: "host"
    volumes:
      - "rabbit:/var/lib/rabbit"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    network_mode: "host"
    volumes:
      - "redis:/data"

volumes:
  mongo: {}
  postgres: {}
  mysql: {}
  rabbit: {}
  redis: {}