version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - 27017
    network_mode: "host"
    volumes:
      - "mongo:/data/db"

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    network_mode: "host"
    volumes:
      - "postgres:/var/lib/postgresql/data"

#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    restart: always
#    expose:
#      - 3306
#    network_mode: "host"
#    volumes:
#      - "mysql:/var/lib/mysql"
#    environment:
#      - "MYSQL_ROOT_PASSWORD=root"

  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    restart: always
    expose:
      - 5672
      - 15672
    network_mode: "host"
    volumes:
      - "rabbit:/var/lib/rabbit"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - 6379
    network_mode: "host"
    volumes:
      - "redis:/data"

#  influxdb:
#    image: influxdb
#    container_name: influxdb
#    restart: always
#    expose:
#      - 8086
#      - 8083
#    network_mode: "host"
#    volumes:
#      - "influxdb:/var/lib/influxdb"
#    environment:
#      - "INFLUXDB_ADMIN_ENABLED=true"
#      - "INFLUXDB_ADMIN_USER=influxdb"
#      - "INFLUXDB_ADMIN_PASSWORD=influxdb"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    network_mode: "host"
    expose:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=127.0.0.1:4160 --data-path=/data
    network_mode: "host"
    depends_on:
      - nsqlookupd
    expose:
      - "4150"
      - "4151"
    volumes:
      - "nsqd:/data"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=127.0.0.1:4161
    network_mode: "host"
    depends_on:
      - nsqlookupd  
    expose:
      - "4171"

volumes:
  mongo: {}
  postgres: {}
  mysql: {}
  rabbit: {}
  redis: {}
  influxdb: {}
  nsqd: {}
